<?php defined('SYS_ROOT') OR die('Direct script access prohibited');

class welcome extends Controller_Core {
	public function index() {
		$view = new View('welcome_view');		
		$view->args = func_get_args();
		$view->render(true);
	}
	
	public function __call($method, $args) {
		echo 'This text is generated by __call. If you expected the index page, 
			you need to use: /welcome/index/foo';
		echo '<br />';
		echo 'You called the method: <strong>'.$method.'</strong><br />';
		echo 'with the following aruments:<br />';
		foreach($args as $a) {
			echo $a.'<br />';
		}
	}
	
}

?>