<?php defined('SYS_ROOT') OR die('Direct script access prohibited'); ?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?php echo $error ?></title>
		<base href="http://php.net/" />
		<style type="text/css">
			#framework_error {
				width: 45em;
				margin: auto;
				padding: 10px 20px;
				background: #eee;
				border: 1px solid #bbb;
			}
			h1 {
				font-size: 20px;
				margin: 0;
			}
			h2 {
				margin: 0;
				font-size: 16px;
			}
			ul.backtrace {
				background: #fff;
				border: 1px solid #bbb;
				padding: 10px 20px;
				margin: 0;
			}
			ul.backtrace li {
				list-style-type: none;
				margin: 0;
				padding: 10px 0;
			}
			li.row0 {
			}
			li.row1 {
			}
			code.block {
				display: block;
			}
			.stats {
				text-align: center;
				font-size: 10px;
				margin: 0;
				padding: 0;
			}
		</style>
	</head>
	<body>
		<div id="framework_error">
			<h1><?php echo htmlspecialchars($error) ?></h1>

		<?php if ( ! empty($line) AND ! empty($file)): ?>
			<p><tt><?php echo $file;?><strong>[<?php echo $line;?>]:</strong></tt></p>
		<?php endif ?>
			<p><code class="block"><?php echo $message ?></code></p>

		<?php if ( ! empty($trace)): ?>
			<h2><?=sliMVC::lang('core.stack_trace');?></h2>
			<?php echo $trace ?>
		<?php endif ?>
		
	</div>
	<div class="stats">Generated by sliMVC v0.9</div>	
</body>
</html>